version: '3.1'
services:
  backend001:                                  # 后端express容器
    container_name: backend001
    restart: always
    build:      # 指定设定上下文根目录，然后以该目录为准指定Dockerfile
      context: ./
      dockerfile: Dockerfile001
#    networks:
#      - myweb
    ports:                              # 映射端口
      - 3001:3001
    command:  "npm start" # 容器创建后执行命令

  backend002:                                  # 后端express容器
    container_name: backend002
    restart: always
    build:      # 指定设定上下文根目录，然后以该目录为准指定Dockerfile
      context: ./
      dockerfile: Dockerfile002

    #    networks:
    #      - myweb
    ports:                              # 映射端口
      - 3002:3002
    command:  "npm start" # 容器创建后执行命令

  frontend:             # 前端容器(运行nginx中的 frontend 项目)
    container_name: frontendTotal
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf #挂载nginx配置
      - ./frontend001/dist:/usr/share/nginx/html/app001  #挂载项目
      - ./frontend002/dist:/usr/share/nginx/html/app002  #挂载项目
#    networks:
#      - myweb

    ports:
      - 80:80                     # 映射端口

    depends_on:     # 依赖于api容器，被依赖容器启动后此web容器才可启动
      - backend001
      - backend002

# networks:
#  myweb:
#    driver: bridge

